# Generated by Django 6.0 on 2025-12-16 13:35

from django.db import migrations, models

GENRES = [
    ("rock", "Рок"),
    ("pop", "Поп"),
    ("hip-hop", "Хип-хоп"),
    ("electronic", "Электроника"),
    ("jazz", "Джаз"),
    ("classical", "Классическая"),
    ("metal", "Метал"),
    ("blues", "Блюз"),
    ("country", "Кантри"),
    ("reggae", "Регги"),
    ("rnb", "R&B"),
    ("indie", "Инди"),
    ("folk", "Фолк"),
    ("punk", "Панк"),
    ("disco", "Диско"),
    ("soul", "Соул"),
    ("trance", "Транс"),
    ("house", "Хаус"),
    ("techno", "Техно"),
    ("dubstep", "Дабстеп"),
]

def populate_genres(apps, schema_editor):
    Genre = apps.get_model('music', 'Genre')
    for code, name in GENRES:
        Genre.objects.get_or_create(code=code, name=name)

def reverse_populate_genres(apps, schema_editor):
    Genre = apps.get_model('music', 'Genre')
    Genre.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название жанра')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название альбома'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя исполнителя'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='Аноним', max_length=100, verbose_name='Имя автора комментария'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(default='Unnamed', max_length=200, verbose_name='Название трека'),
        ),
        migrations.AlterField(
            model_name='track',
            name='uploaded_by',
            field=models.CharField(default='Аноним', max_length=100, verbose_name='Ник загрузившего'),
        ),
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='music.Genre', verbose_name='Жанры'),
        ),
        # ЗАПОЛНЕНИЕ ЖАНРАМИ — ВСТАВЛЕНО СЮДА
        migrations.RunPython(populate_genres, reverse_populate_genres),
    ]